<a href="https://colab.research.google.com/github/virf96/Neural-Networks/blob/main/Softmax_en_redes_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import make_classification
from sklearn.preprocessing import OneHotEncoder

import plotly.graph_objects as go 
import numpy as np

In [ ]:
X, Y = make_classification(10000, n_classes=3, n_informative=8)

In [ ]:
np.unique(Y)

array([0, 1, 2])

In [ ]:
Y[:5]

array([2, 0, 0, 2, 0])

### OneHot Encoding

#### Sklearn

In [ ]:
one = OneHotEncoder()
Y_oneHot=one.fit_transform(Y.reshape(-1,1))

In [ ]:
Y_oneHot.toarray()

array([[0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [ ]:
Y

array([2, 0, 0, ..., 0, 2, 1])

#### Numpy

In [ ]:
Y_oneHot = np.eye(3)[Y]

In [ ]:
Y_oneHot

array([[0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [ ]:
Y_oneHot.shape

(10000, 3)

### train test

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
xt,xv,yt,yv = train_test_split(X,Y_oneHot)

In [ ]:
xt.shape, yt.shape

((7500, 20), (7500, 3))

### Red neuronal

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, InputLayer
from tensorflow.keras.losses import CategoricalCrossentropy ## loss para multiclasificacion 
from tensorflow.keras.optimizers import Adam

In [ ]:
X.shape

(10000, 20)

In [ ]:
model = Sequential()
model.add(InputLayer(input_shape=(20)))
model.add(Dense(15, activation="relu"))
model.add(Dense(8, activation="relu"))
model.add(Dense(3, activation="softmax"))## Capa de salida, el numero de neuronas debe ser igual al numero de clases del dataset
model.compile(loss= CategoricalCrossentropy(), optimizer = Adam())

In [ ]:
history = model.fit(x=xt,y=yt, epochs=100, batch_size = 128, validation_data=(xv,yv))

Epoch 1/100
59/59 [==============================] - 0s 3ms/step - loss: 1.7152 - val_loss: 1.2356
Epoch 2/100
59/59 [==============================] - 0s 2ms/step - loss: 1.1533 - val_loss: 1.0204
Epoch 3/100
59/59 [==============================] - 0s 2ms/step - loss: 0.9731 - val_loss: 0.8873
Epoch 4/100
59/59 [==============================] - 0s 2ms/step - loss: 0.8424 - val_loss: 0.7610
Epoch 5/100
59/59 [==============================] - 0s 2ms/step - loss: 0.7296 - val_loss: 0.6645
Epoch 6/100
59/59 [==============================] - 0s 2ms/step - loss: 0.6354 - val_loss: 0.5932
Epoch 7/100
59/59 [==============================] - 0s 2ms/step - loss: 0.5704 - val_loss: 0.5406
Epoch 8/100
59/59 [==============================] - 0s 2ms/step - loss: 0.5171 - val_loss: 0.5018
Epoch 9/100
59/59 [==============================] - 0s 2ms/step - loss: 0.4748 - val_loss: 0.4694
Epoch 10/100
59/59 [==============================] - 0s 2ms/step - loss: 0.4600 - val_loss: 0.4465
Epoch 11/

59/59 [==============================] - 0s 2ms/step - loss: 0.2095 - val_loss: 0.2554
Epoch 84/100
59/59 [==============================] - 0s 2ms/step - loss: 0.2075 - val_loss: 0.2542
Epoch 85/100
59/59 [==============================] - 0s 2ms/step - loss: 0.1978 - val_loss: 0.2548
Epoch 86/100
59/59 [==============================] - 0s 2ms/step - loss: 0.1934 - val_loss: 0.2527
Epoch 87/100
59/59 [==============================] - 0s 2ms/step - loss: 0.2040 - val_loss: 0.2508
Epoch 88/100
59/59 [==============================] - 0s 2ms/step - loss: 0.1904 - val_loss: 0.2518
Epoch 89/100
59/59 [==============================] - 0s 2ms/step - loss: 0.2018 - val_loss: 0.2526
Epoch 90/100
59/59 [==============================] - 0s 2ms/step - loss: 0.1933 - val_loss: 0.2552
Epoch 91/100
59/59 [==============================] - 0s 2ms/step - loss: 0.1883 - val_loss: 0.2538
Epoch 92/100
59/59 [==============================] - 0s 2ms/step - loss: 0.1957 - val_loss: 0.2519
Epoch 93/100


### Funcion de perdida

In [ ]:
fig = go.Figure(layout = dict(title="Loss"))
fig.add_trace(go.Scatter(x=list(range(len(history.history["loss"]))),y=history.history["loss"], name="loss"))
fig.add_trace(go.Scatter(x=list(range(len(history.history["loss"]))),y=history.history["val_loss"], name="val_loss"))
fig.show()

### Accuracy 

In [ ]:
np.sum(model.predict(X),axis=1) ### el predict regresa las probabilidades

array([1.        , 1.0000001 , 1.        , ..., 1.        , 1.        ,
       0.99999994], dtype=float32)

In [ ]:
model.predict_classes(X)

c:\program files\python38\lib\site-packages\tensorflow\python\keras\engine\sequential.py:455: UserWarning:

`model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).



array([2, 0, 0, ..., 0, 2, 1], dtype=int64)

In [ ]:
np.argmax(model.predict(X),axis=1) ### para devolver las clases predichas

array([2, 0, 0, ..., 0, 2, 1], dtype=int64)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
y_pred = np.argmax(model.predict(X),axis=1)
accuracy_score(Y,y_pred)

0.9544

### metricas de train  y test

In [ ]:
yt

array([[0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       ...,
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [ ]:
np.argmax(yt,axis=1)

array([1, 0, 0, ..., 1, 0, 2], dtype=int64)

In [ ]:
y_pred = np.argmax(model.predict(xt),axis=1)
accuracy_score(np.argmax(yt,axis=1),y_pred)

0.9368

In [ ]:
y_pred = np.argmax(model.predict(xv),axis=1)
accuracy_score(np.argmax(yv,axis=1),y_pred)

0.9176

### Logits en clasificacion 

Los logits son las salidas de la capa antes de la activacion, es decir $$z^{[l]}$$

In [ ]:
model = Sequential()
model.add(InputLayer(input_shape=(20)))
model.add(Dense(15, activation="relu"))
model.add(Dense(8, activation="relu"))
model.add(Dense(3)) ### Capa sin activacion o identidad, linear
model.compile(loss= CategoricalCrossentropy(from_logits=True), optimizer = Adam())

In [ ]:
history = model.fit(x=xt,y=yt, epochs=100, batch_size = 128, validation_data=(xv,yv))

Epoch 1/100
59/59 [==============================] - 0s 4ms/step - loss: 1.1052 - val_loss: 0.9665
Epoch 2/100
59/59 [==============================] - 0s 3ms/step - loss: 0.9359 - val_loss: 0.8608
Epoch 3/100
59/59 [==============================] - 0s 2ms/step - loss: 0.8414 - val_loss: 0.7747
Epoch 4/100
59/59 [==============================] - 0s 2ms/step - loss: 0.7559 - val_loss: 0.6996
Epoch 5/100
59/59 [==============================] - 0s 2ms/step - loss: 0.6820 - val_loss: 0.6357
Epoch 6/100
59/59 [==============================] - 0s 2ms/step - loss: 0.6122 - val_loss: 0.5798
Epoch 7/100
59/59 [==============================] - 0s 2ms/step - loss: 0.5747 - val_loss: 0.5327
Epoch 8/100
59/59 [==============================] - 0s 2ms/step - loss: 0.5146 - val_loss: 0.4942
Epoch 9/100
59/59 [==============================] - 0s 2ms/step - loss: 0.4702 - val_loss: 0.4620
Epoch 10/100
59/59 [==============================] - 0s 2ms/step - loss: 0.4401 - val_loss: 0.4341
Epoch 11/

59/59 [==============================] - 0s 2ms/step - loss: 0.1856 - val_loss: 0.2370
Epoch 84/100
59/59 [==============================] - 0s 2ms/step - loss: 0.1812 - val_loss: 0.2325
Epoch 85/100
59/59 [==============================] - 0s 2ms/step - loss: 0.1832 - val_loss: 0.2334
Epoch 86/100
59/59 [==============================] - 0s 2ms/step - loss: 0.1694 - val_loss: 0.2328
Epoch 87/100
59/59 [==============================] - 0s 2ms/step - loss: 0.1583 - val_loss: 0.2338
Epoch 88/100
59/59 [==============================] - 0s 2ms/step - loss: 0.1782 - val_loss: 0.2313
Epoch 89/100
59/59 [==============================] - 0s 2ms/step - loss: 0.1716 - val_loss: 0.2322
Epoch 90/100
59/59 [==============================] - 0s 2ms/step - loss: 0.1739 - val_loss: 0.2309
Epoch 91/100
59/59 [==============================] - 0s 2ms/step - loss: 0.1715 - val_loss: 0.2340
Epoch 92/100
59/59 [==============================] - 0s 2ms/step - loss: 0.1653 - val_loss: 0.2308
Epoch 93/100


In [ ]:
fig = go.Figure(layout = dict(title="Loss"))
fig.add_trace(go.Scatter(x=list(range(len(history.history["loss"]))),y=history.history["loss"], name="loss"))
fig.add_trace(go.Scatter(x=list(range(len(history.history["loss"]))),y=history.history["val_loss"], name="val_loss"))
fig.show()

#### prediccion con logits 

In [ ]:
np.argmax(model.predict(xt),axis = 1)

array([1, 0, 0, ..., 1, 0, 2], dtype=int64)

In [ ]:
y_pred = np.argmax(model.predict(xt),axis=1)
accuracy_score(np.argmax(yt,axis=1),y_pred)

0.946

### Callbacks

Un callback es una funcion que se ejecuta en un evento determinado


En nuestro caso de redes neuronales, los callback son funciones que se ejecutaran en momentos especificos del entrenamiento de la red.

#### Checkpoints

Un checpoint es un estado del modelo que guardamos

In [ ]:
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.models import load_model

In [ ]:
model = Sequential()
model.add(InputLayer(input_shape=(20)))
model.add(Dense(15, activation="relu"))
model.add(Dense(8, activation="relu"))
model.add(Dense(3)) ### Capa sin activacion o identidad, linear
model.compile(loss= CategoricalCrossentropy(from_logits=True), optimizer = Adam())

In [ ]:
!mkdir checkpoints

In [ ]:
checkpoints = ModelCheckpoint(
                            "./checkpoints/checpoint.h5",
                            monitor='val_loss', ## que funcion monitorea para crear el checkpoint
                            verbose=10, ## imprima que guardo un checpoint
                            save_best_only=True, ## solo guarde el mejor model
                            save_weights_only=False, ## Nos guarda la arquitectura y los pesos
                            mode="min", ### Cuando guardar el checkpoint, en este caso, cada nuevo minimo en la funcion de val_loss
                            save_freq='epoch',) ### Cada cuando guarda el checkpoint

In [ ]:
history = model.fit(x=xt,y=yt, epochs=100, batch_size = 128, validation_data=(xv,yv), callbacks=[checkpoints])

Epoch 1/100
59/59 [==============================] - 0s 4ms/step - loss: 0.1490 - val_loss: 0.2021

Epoch 00001: val_loss did not improve from 0.19987
Epoch 2/100
59/59 [==============================] - 0s 3ms/step - loss: 0.1498 - val_loss: 0.2048

Epoch 00002: val_loss did not improve from 0.19987
Epoch 3/100
59/59 [==============================] - 0s 3ms/step - loss: 0.1489 - val_loss: 0.2008

Epoch 00003: val_loss did not improve from 0.19987
Epoch 4/100
59/59 [==============================] - 0s 2ms/step - loss: 0.1491 - val_loss: 0.2030

Epoch 00004: val_loss did not improve from 0.19987
Epoch 5/100
59/59 [==============================] - 0s 2ms/step - loss: 0.1496 - val_loss: 0.2032

Epoch 00005: val_loss did not improve from 0.19987
Epoch 6/100
59/59 [==============================] - 0s 2ms/step - loss: 0.1492 - val_loss: 0.2056

Epoch 00006: val_loss did not improve from 0.19987
Epoch 7/100
59/59 [==============================] - 0s 2ms/step - loss: 0.1494 - val_loss: 0.

59/59 [==============================] - 0s 2ms/step - loss: 0.1449 - val_loss: 0.2038

Epoch 00055: val_loss did not improve from 0.19987
Epoch 56/100
59/59 [==============================] - 0s 2ms/step - loss: 0.1439 - val_loss: 0.2068

Epoch 00056: val_loss did not improve from 0.19987
Epoch 57/100
59/59 [==============================] - 0s 2ms/step - loss: 0.1449 - val_loss: 0.2034

Epoch 00057: val_loss did not improve from 0.19987
Epoch 58/100
59/59 [==============================] - 0s 2ms/step - loss: 0.1441 - val_loss: 0.2067

Epoch 00058: val_loss did not improve from 0.19987
Epoch 59/100
59/59 [==============================] - 0s 2ms/step - loss: 0.1456 - val_loss: 0.2037

Epoch 00059: val_loss did not improve from 0.19987
Epoch 60/100
59/59 [==============================] - 0s 2ms/step - loss: 0.1445 - val_loss: 0.2051

Epoch 00060: val_loss did not improve from 0.19987
Epoch 61/100
59/59 [==============================] - 0s 2ms/step - loss: 0.1440 - val_loss: 0.2022



In [ ]:
model = load_model("./checkpoints/checpoint.h5")

In [ ]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_15 (Dense)             (None, 15)                315       
_________________________________________________________________
dense_16 (Dense)             (None, 8)                 128       
_________________________________________________________________
dense_17 (Dense)             (None, 3)                 27        
Total params: 470
Trainable params: 470
Non-trainable params: 0
_________________________________________________________________


In [ ]:
y_pred = np.argmax(model.predict(xt),axis=1)
accuracy_score(np.argmax(yt,axis=1),y_pred)

0.9556

#### EarlyStopping

In [ ]:
from scipy.io import loadmat

In [ ]:
data = loadmat("data.mat")

In [ ]:
xt = data["X"]
yt = data["y"]
xv= data["Xval"]
yv = data["yval"]

In [ ]:
np.unique(yt)

array([0, 1], dtype=uint8)

In [ ]:
from tensorflow.keras.losses import BinaryCrossentropy
from tensorflow.keras.callbacks import EarlyStopping

In [ ]:
xt.shape

(211, 2)

In [ ]:
model = Sequential()
model.add(InputLayer(input_shape=(2)))
model.add(Dense(15, activation="relu"))
model.add(Dense(8, activation="relu"))
model.add(Dense(15, activation="relu"))
model.add(Dense(8, activation="relu"))
model.add(Dense(1)) ### Capa sin activacion o identidad, linear
model.compile(loss= BinaryCrossentropy(from_logits=True), optimizer = Adam())

In [ ]:
history = model.fit(x=xt,y=yt, epochs=300, batch_size = 128, validation_data=(xv,yv),)

Epoch 1/300
2/2 [==============================] - 0s 83ms/step - loss: 0.6927 - val_loss: 0.6882
Epoch 2/300
2/2 [==============================] - 0s 14ms/step - loss: 0.6891 - val_loss: 0.6843
Epoch 3/300
2/2 [==============================] - 0s 14ms/step - loss: 0.6855 - val_loss: 0.6806
Epoch 4/300
2/2 [==============================] - 0s 14ms/step - loss: 0.6826 - val_loss: 0.6770
Epoch 5/300
2/2 [==============================] - 0s 14ms/step - loss: 0.6802 - val_loss: 0.6737
Epoch 6/300
2/2 [==============================] - 0s 15ms/step - loss: 0.6779 - val_loss: 0.6705
Epoch 7/300
2/2 [==============================] - 0s 18ms/step - loss: 0.6750 - val_loss: 0.6673
Epoch 8/300
2/2 [==============================] - 0s 15ms/step - loss: 0.6714 - val_loss: 0.6639
Epoch 9/300
2/2 [==============================] - 0s 16ms/step - loss: 0.6687 - val_loss: 0.6604
Epoch 10/300
2/2 [==============================] - 0s 27ms/step - loss: 0.6651 - val_loss: 0.6567
Epoch 11/300
2/2 [=

Epoch 84/300
2/2 [==============================] - 0s 15ms/step - loss: 0.2333 - val_loss: 0.2382
Epoch 85/300
2/2 [==============================] - 0s 15ms/step - loss: 0.2220 - val_loss: 0.2370
Epoch 86/300
2/2 [==============================] - 0s 15ms/step - loss: 0.2207 - val_loss: 0.2365
Epoch 87/300
2/2 [==============================] - 0s 14ms/step - loss: 0.2322 - val_loss: 0.2367
Epoch 88/300
2/2 [==============================] - 0s 16ms/step - loss: 0.2488 - val_loss: 0.2373
Epoch 89/300
2/2 [==============================] - 0s 15ms/step - loss: 0.2313 - val_loss: 0.2379
Epoch 90/300
2/2 [==============================] - 0s 15ms/step - loss: 0.2409 - val_loss: 0.2388
Epoch 91/300
2/2 [==============================] - 0s 14ms/step - loss: 0.2233 - val_loss: 0.2388
Epoch 92/300
2/2 [==============================] - ETA: 0s - loss: 0.223 - 0s 15ms/step - loss: 0.2267 - val_loss: 0.2380
Epoch 93/300
2/2 [==============================] - 0s 16ms/step - loss: 0.2346 - val

Epoch 166/300
2/2 [==============================] - 0s 15ms/step - loss: 0.2068 - val_loss: 0.2286
Epoch 167/300
2/2 [==============================] - 0s 14ms/step - loss: 0.2076 - val_loss: 0.2287
Epoch 168/300
2/2 [==============================] - 0s 14ms/step - loss: 0.2121 - val_loss: 0.2287
Epoch 169/300
2/2 [==============================] - 0s 14ms/step - loss: 0.2228 - val_loss: 0.2286
Epoch 170/300
2/2 [==============================] - 0s 18ms/step - loss: 0.2015 - val_loss: 0.2292
Epoch 171/300
2/2 [==============================] - 0s 16ms/step - loss: 0.2301 - val_loss: 0.2302
Epoch 172/300
2/2 [==============================] - 0s 15ms/step - loss: 0.2124 - val_loss: 0.2311
Epoch 173/300
2/2 [==============================] - 0s 14ms/step - loss: 0.2143 - val_loss: 0.2310
Epoch 174/300
2/2 [==============================] - 0s 15ms/step - loss: 0.2102 - val_loss: 0.2308
Epoch 175/300
2/2 [==============================] - 0s 16ms/step - loss: 0.2129 - val_loss: 0.2299


Epoch 248/300
2/2 [==============================] - 0s 17ms/step - loss: 0.2166 - val_loss: 0.2269
Epoch 249/300
2/2 [==============================] - 0s 19ms/step - loss: 0.2068 - val_loss: 0.2268
Epoch 250/300
2/2 [==============================] - 0s 15ms/step - loss: 0.1909 - val_loss: 0.2273
Epoch 251/300
2/2 [==============================] - 0s 14ms/step - loss: 0.2006 - val_loss: 0.2269
Epoch 252/300
2/2 [==============================] - 0s 16ms/step - loss: 0.2032 - val_loss: 0.2271
Epoch 253/300
2/2 [==============================] - 0s 14ms/step - loss: 0.2067 - val_loss: 0.2271
Epoch 254/300
2/2 [==============================] - 0s 14ms/step - loss: 0.2111 - val_loss: 0.2275
Epoch 255/300
2/2 [==============================] - 0s 14ms/step - loss: 0.2169 - val_loss: 0.2283
Epoch 256/300
2/2 [==============================] - 0s 14ms/step - loss: 0.2026 - val_loss: 0.2284
Epoch 257/300
2/2 [==============================] - 0s 16ms/step - loss: 0.1976 - val_loss: 0.2276


In [ ]:
fig = go.Figure(layout = dict(title="Loss"))
fig.add_trace(go.Scatter(x=list(range(len(history.history["loss"]))),y=history.history["loss"], name="loss"))
fig.add_trace(go.Scatter(x=list(range(len(history.history["loss"]))),y=history.history["val_loss"], name="val_loss"))
fig.show()

In [ ]:
1e-5 - .00001

0.0

In [ ]:
early = EarlyStopping( ## detiene el entrenamiento cuando la funcion que monitorea no sigue decreciendo 
                    monitor='val_loss', ## monitore la funcion de perdida
                    min_delta=1e-5, ## cuanto debe cambiar para conciderar que no esta mejorando
                    patience=1, ## cuantas iteraciones espera a el cambio antes de detener el entrenamiento
                    verbose=10,
                    mode='min',)

In [ ]:
model = Sequential()
model.add(InputLayer(input_shape=(2)))
model.add(Dense(15, activation="relu"))
model.add(Dense(8, activation="relu"))
model.add(Dense(15, activation="relu"))
model.add(Dense(8, activation="relu"))
model.add(Dense(1)) ### Capa sin activacion o identidad, linear
model.compile(loss= BinaryCrossentropy(from_logits=True), optimizer = Adam())

In [ ]:
history = model.fit(x=xt,y=yt, epochs=10000, batch_size = 128, validation_data=(xv,yv), callbacks=[early, checkpoints])

Epoch 1/10000
2/2 [==============================] - 0s 84ms/step - loss: 0.6794 - val_loss: 0.6792

Epoch 00001: val_loss did not improve from 0.19987
Epoch 2/10000
2/2 [==============================] - 0s 13ms/step - loss: 0.6774 - val_loss: 0.6767

Epoch 00002: val_loss did not improve from 0.19987
Epoch 3/10000
2/2 [==============================] - 0s 14ms/step - loss: 0.6729 - val_loss: 0.6743

Epoch 00003: val_loss did not improve from 0.19987
Epoch 4/10000
2/2 [==============================] - 0s 15ms/step - loss: 0.6717 - val_loss: 0.6719

Epoch 00004: val_loss did not improve from 0.19987
Epoch 5/10000
2/2 [==============================] - 0s 27ms/step - loss: 0.6671 - val_loss: 0.6695

Epoch 00005: val_loss did not improve from 0.19987
Epoch 6/10000
2/2 [==============================] - 0s 17ms/step - loss: 0.6668 - val_loss: 0.6671

Epoch 00006: val_loss did not improve from 0.19987
Epoch 7/10000
2/2 [==============================] - 0s 15ms/step - loss: 0.6646 - val_l


Epoch 00054: val_loss did not improve from 0.19987
Epoch 55/10000
2/2 [==============================] - 0s 15ms/step - loss: 0.4442 - val_loss: 0.4467

Epoch 00055: val_loss did not improve from 0.19987
Epoch 56/10000
2/2 [==============================] - 0s 14ms/step - loss: 0.4359 - val_loss: 0.4400

Epoch 00056: val_loss did not improve from 0.19987
Epoch 57/10000
2/2 [==============================] - 0s 16ms/step - loss: 0.4251 - val_loss: 0.4331

Epoch 00057: val_loss did not improve from 0.19987
Epoch 58/10000
2/2 [==============================] - 0s 16ms/step - loss: 0.4231 - val_loss: 0.4261

Epoch 00058: val_loss did not improve from 0.19987
Epoch 59/10000
2/2 [==============================] - 0s 16ms/step - loss: 0.4212 - val_loss: 0.4189

Epoch 00059: val_loss did not improve from 0.19987
Epoch 60/10000
2/2 [==============================] - 0s 14ms/step - loss: 0.4150 - val_loss: 0.4116

Epoch 00060: val_loss did not improve from 0.19987
Epoch 61/10000
2/2 [==========

In [ ]:
fig = go.Figure(layout = dict(title="Loss"))
fig.add_trace(go.Scatter(x=list(range(len(history.history["loss"]))),y=history.history["loss"], name="loss"))
fig.add_trace(go.Scatter(x=list(range(len(history.history["loss"]))),y=history.history["val_loss"], name="val_loss"))
fig.show()

### TensorBoard